app:
  image: 996818459618.dkr.ecr.us-east-1.amazonaws.com/vprofile_app_image
  tag: 1e15bb7
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  defaultUser: guest
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
db:
  image: vprocontainers/vprofiledb
  tag: latest
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 8Gi
  defaultUser: root
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
memcached:
  image: memcached
  tag: latest
  replicas: 1
  containerPort: 11211
  servicePort: 11211
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
rabbitmq:
  image: rabbitmq
  tag: latest
  replicas: 1
  containerPort: 5672
  servicePort: 5672
  defaultUser: guest
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
initcontainers:
  image: busybox
  tag: latest
ingress:
  enabled: true
  host: ""
  servicePort: 80
  certificateArn: ""
dockerregistry:
  enabled: false
  server: https://index.docker.io/v1/
  username: ""
  password: ""
  email: ""
secrets:
  dbPassword: vprodbpass
  rmqPassword: guest
