apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
type: Opaque
data:
  db-pass: {{ .Values.secrets.dbPassword | b64enc }}
  rmq-pass: {{ .Values.secrets.rmqPassword | b64enc }}
